// models/index.js - Sequelize Models Index
const sequelize = require("../config/db");

// Import all models
const Company = require("./Company.model");
const User = require("./User.model");
const Branch = require("./Branch.model");
const Employee = require("./Employee.model");
const Attendance = require("./Attendance.model");
const Punch = require("./Punch.model");
const Leave = require("./Leave.model");
const Holiday = require("./Holiday.model");
const Payroll = require("./Payroll.model");
const Payslip = require("./Payslip.model");
const AuditLog = require("./AuditLog.model");
const Notification = require("./Notification.model");
const CompanySetting = require("./CompanySetting.model");

// Define associations
// Company -> Users
Company.hasMany(User, { foreignKey: "company_id", as: "users" });
User.belongsTo(Company, { foreignKey: "company_id", as: "company" });

// Company -> Branches
Company.hasMany(Branch, { foreignKey: "company_id", as: "branches" });
Branch.belongsTo(Company, { foreignKey: "company_id", as: "company" });

// Company -> Employees
Company.hasMany(Employee, { foreignKey: "company_id", as: "employees" });
Employee.belongsTo(Company, { foreignKey: "company_id", as: "company" });

// Branch -> Employees
Branch.hasMany(Employee, { foreignKey: "branch_id", as: "employees" });
Employee.belongsTo(Branch, { foreignKey: "branch_id", as: "branch" });

// User -> Employee (one-to-one)
User.hasOne(Employee, { foreignKey: "user_id", as: "employee" });
Employee.belongsTo(User, { foreignKey: "user_id", as: "user" });

// Branch -> Manager (Employee)
Branch.belongsTo(Employee, { foreignKey: "manager_id", as: "manager" });
Employee.hasOne(Branch, { foreignKey: "manager_id", as: "managed_branch" });

// Employee -> Attendance
Employee.hasMany(Attendance, { foreignKey: "employee_id", as: "attendances" });
Attendance.belongsTo(Employee, { foreignKey: "employee_id", as: "employee" });

// Attendance -> Punches
Attendance.hasMany(Punch, { foreignKey: "attendance_id", as: "punches" });
Punch.belongsTo(Attendance, { foreignKey: "attendance_id", as: "attendance" });

// Branch -> Punches
Branch.hasMany(Punch, { foreignKey: "branch_id", as: "punches" });
Punch.belongsTo(Branch, { foreignKey: "branch_id", as: "branch" });

// Employee -> Leaves
Employee.hasMany(Leave, { foreignKey: "employee_id", as: "leaves" });
Leave.belongsTo(Employee, { foreignKey: "employee_id", as: "employee" });

// User -> Leaves (reviewed by)
User.hasMany(Leave, { foreignKey: "reviewed_by", as: "reviewed_leaves" });
Leave.belongsTo(User, { foreignKey: "reviewed_by", as: "reviewer" });

// Company -> Holidays
Company.hasMany(Holiday, { foreignKey: "company_id", as: "holidays" });
Holiday.belongsTo(Company, { foreignKey: "company_id", as: "company" });

// Branch -> Holidays
Branch.hasMany(Holiday, { foreignKey: "branch_id", as: "holidays" });
Holiday.belongsTo(Branch, { foreignKey: "branch_id", as: "branch" });

// Employee -> Payrolls
Employee.hasMany(Payroll, { foreignKey: "employee_id", as: "payrolls" });
Payroll.belongsTo(Employee, { foreignKey: "employee_id", as: "employee" });

// User -> Payrolls (processed by)
User.hasMany(Payroll, { foreignKey: "processed_by", as: "processed_payrolls" });
Payroll.belongsTo(User, { foreignKey: "processed_by", as: "processor" });

// Payroll -> Payslip (one-to-one)
Payroll.hasOne(Payslip, { foreignKey: "payroll_id", as: "payslip" });
Payslip.belongsTo(Payroll, { foreignKey: "payroll_id", as: "payroll" });

// Employee -> Payslips
Employee.hasMany(Payslip, { foreignKey: "employee_id", as: "payslips" });
Payslip.belongsTo(Employee, { foreignKey: "employee_id", as: "employee" });

// User -> Payslips (generated by)
User.hasMany(Payslip, { foreignKey: "generated_by", as: "generated_payslips" });
Payslip.belongsTo(User, { foreignKey: "generated_by", as: "generator" });

// User -> AuditLogs
User.hasMany(AuditLog, { foreignKey: "performed_by", as: "audit_logs" });
AuditLog.belongsTo(User, { foreignKey: "performed_by", as: "performer" });

// User -> Notifications
User.hasMany(Notification, { foreignKey: "user_id", as: "notifications" });
Notification.belongsTo(User, { foreignKey: "user_id", as: "user" });

// Company -> Notifications
Company.hasMany(Notification, { foreignKey: "company_id", as: "notifications" });
Notification.belongsTo(Company, { foreignKey: "company_id", as: "company" });

// Company -> CompanySettings
Company.hasMany(CompanySetting, { foreignKey: "company_id", as: "settings" });
CompanySetting.belongsTo(Company, { foreignKey: "company_id", as: "company" });

// Export all models and sequelize instance
module.exports = {
  sequelize,
  Sequelize: require("sequelize"),
  Company,
  User,
  Branch,
  Employee,
  Attendance,
  Punch,
  Leave,
  Holiday,
  Payroll,
  Payslip,
  AuditLog,
  Notification,
  CompanySetting,
};